### PR TITLE
add option to just make api calls and not upload vcl

### PR DESCRIPTION
**Pull request by aintgoin2goa**

### CODE REVIEW

**Comment by matthew-andrews** [comment]
would it be possible to just have it default to no VCL unless you specify a folder and entry VCL?  or is there a good reason to force people to explicitly opt out of having VCL?

**Comment by aintgoin2goa** [comment]
Not really, I just though it made it clearer for people reading the makefile what is going on

**Comment by matthew-andrews** [comment]
i think it would be clear that by ommitting VCL files, it won't use them, fewer options is my personal preference, but no harm with your approach.

what do @jonnangle / @keithamus think?

**Comment by keithamus** [comment]
I agree with @matthew-andrews. Seems more intuitive to specify a VCL entry file.

**Comment by aintgoin2goa** [comment]
I just discovered that I couldn't actually avoid using vcl so there's not actually a use case for this any more...

**Comment by matthew-andrews** [comment]
what was the thing that stopped you not not using vcl?

**Comment by aintgoin2goa** [comment]
Setting the correct host header so Heroku understands - is there a way to do this?

**Comment by lucas42** [comment]
You could configure your heroku app to respond to the original host header being sent through.  (or is there problems with that for multi-region apps?)

**Comment by aintgoin2goa** [comment]
I didn't know I could do that!  But, yeah, this is multi-region and therefore has 2 apps which would respond to the same host header so I guess that won't work...

**Comment by aintgoin2goa** [comment]
I'm going to close this PR as no-one actually needs this feature right now

**Pull request closed without merging**
