### PR TITLE
Improve error handling and fix missing folder error

### PR DESCRIPTION
**Pull request by quarterto**

### CODE REVIEW

**Comment by quarterto** [comment]
Tests are failing because of some missing Fastly mocks. I'm looking into it.

**Comment by quarterto** [comment]
I've added the missing mocks. Would it be possible to derive these from `fastly/lib/api.js`?

**Comment by matthew-andrews** [comment]
hipster symbols 👨 

+1

**Comment by quarterto** [comment]
`process.exit(1)` isn't being called...

**Comment by quarterto** [comment]
@matthew-andrews is that "+1" as in "lgtm, merge it"?

**Comment by matthew-andrews** [comment]
yup

**Pull request merged**
